version: "3.5"

services:
  
  proxy:
    build: .
    image: go-horse
    network_mode: bridge
    ports: 
      - 7070:8080
    environment: 
      - DOCKER_API_VERSION=1.39
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - LOG_LEVEL=debug
      - PRETTY_LOG=true
      - PORT=:8080
      - JS_FILTERS_PATH=/app/go-horse/filters
      - GO_PLUGINS_PATH=/app/go-horse/plugins
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/go-horse:/app/go-horse
