version: "3.5"

services:
  
  proxy:
    build: .
    image: go-horse
    network_mode: bridge
    ports: 
      - 8080:8080
    environment: 
      - DOCKER_API_VERSION=1.39
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - LOG_LEVEL=debug
      - PRETTY_LOG=true
      - PORT=:8080
      - JS_FILTERS_PATH=/app/go-horse/filters
      - GO_PLUGINS_PATH=/app/go-horse/plugins
      - TOKEN_VALIDATION_ENDPOINT=http://172.24.40.4:3000/info
      - ACL_AUTHORIZE_ENDPOINT=http://172.24.40.4:4466/warden/subjects/authorize
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/go-horse:/app/go-horse
