version: "3.5"

services:
  
  proxy:
    build: .
    image: go-horse
    network_mode: bridge
    ports: 
      - 8080:8080
    environment: 
      - GOHORSE_DOCKER_API_VERSION=1.39
      - GOHORSE_DOCKER_SOCK_URL=unix:///var/run/docker.sock
      - GOHORSE_TARGET_HOST_NAME=http://go-horse
      - GOHORSE_LOG_LEVEL=debug
      - GOHORSE_PRETTY_LOG=true
      - GOHORSE_PORT=:8080
      - GOHORSE_JS_FILTERS_PATH=/app/go-horse/filters
      - GOHORSE_GO_PLUGINS_PATH=/app/go-horse/plugins
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/go-horse:/app/go-horse
